// Copyright (c) Richard D. Kiernan.
// Licensed under the Business Source License 1.1. See LICENSE for details.

using System.Net;
using System.Text;
using LinuxMadeSane.Application.Contracts.EdgeGateway;
using LinuxMadeSane.Core.Enums;
using LinuxMadeSane.Core.Models.EdgeGateway;

namespace LinuxMadeSane.Application.Services.EdgeGateway;

public sealed class EdgeGatewayCaddyfileGenerator(EdgeGatewayOptions options)
{
    public const string RemoteLmsRelayImportPath = "/etc/caddy/linuxmadesane/remote-lms-relays.caddy";

    public string Generate(IReadOnlyList<EdgeGatewayRoute> routes)
    {
        var enabledRoutes = routes
            .Where(static item => item.Enabled)
            .OrderBy(static item => item.Hostname, StringComparer.OrdinalIgnoreCase)
            .ThenByDescending(static item => EdgeGatewayRouteValidator.NormalizePathPrefix(item.TargetPathPrefix).Length)
            .ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Linux Made Sane. Do not edit manually.");
        builder.AppendLine("# Manage Edge Gateway routes in LMS.");
        builder.AppendLine();

        var localOrigin = ResolveLocalOrigin(options.CaddyLocalServiceUrl);
        builder.AppendLine($"{localOrigin.CaddySiteAddress} {{");
        if (localOrigin.UseInternalTls)
        {
            builder.AppendLine("    tls internal");
        }

        builder.AppendLine("    encode zstd gzip");
        builder.AppendLine();
        builder.AppendLine($"    import {RemoteLmsRelayImportPath}");
        builder.AppendLine();

        foreach (var route in enabledRoutes)
        {
            EdgeGatewayRouteValidator.ValidateRoute(route);

            var matcherName = BuildMatcherName(route);
            var authMatcherName = BuildAuthMatcherName(route);
            builder.AppendLine($"    # Route: {SanitizeComment(route.DisplayName)}");
            if (!string.IsNullOrWhiteSpace(route.Notes))
            {
                builder.AppendLine($"    # {SanitizeComment(route.Notes)}");
            }

            if (route.AuthMode != EdgeGatewayAuthMode.PassThrough)
            {
                var authAssetMatcherName = BuildAuthAssetMatcherName(route);
                var authReturnMatcherName = BuildAuthReturnMatcherName(route);
                builder.AppendLine($"    @{authMatcherName} {{");
                builder.AppendLine($"        host {route.Hostname}");
                builder.AppendLine($"        path {EdgeGatewayAuthenticationPaths.Login} {EdgeGatewayAuthenticationPaths.ApiPrefix}/* /InitialSetup /initial-setup /auth/initial-setup/*");
                builder.AppendLine("    }");
                builder.AppendLine($"    handle @{authMatcherName} {{");
                builder.AppendLine($"        reverse_proxy 127.0.0.1:{Math.Clamp(options.LmsForwardAuthPort, 1, 65535)} {{");
                builder.AppendLine("            header_up Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Proto https");
                builder.AppendLine("            header_up X-Forwarded-Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Port 443");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine($"    @{authAssetMatcherName} {{");
                builder.AppendLine($"        host {route.Hostname}");
                builder.AppendLine("        path /scripts/theme*.js /scripts/passkeys*.js /styles/* /lib/xterm/* /lib/pdfjs/pdf_viewer*.css /app*.css /LinuxMadeSane.Web*.styles.css /Components/Pages/Login* /Components/Pages/InitialSetup* /images/lms-auth-panel.png /images/lms-splash.png /images/lms-logo-180.png /favicon.png /favicon.ico");
                builder.AppendLine("    }");
                builder.AppendLine($"    handle @{authAssetMatcherName} {{");
                builder.AppendLine($"        reverse_proxy 127.0.0.1:{Math.Clamp(options.LmsForwardAuthPort, 1, 65535)} {{");
                builder.AppendLine("            header_up Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Proto https");
                builder.AppendLine("            header_up X-Forwarded-Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Port 443");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine();
                builder.AppendLine($"    @{authReturnMatcherName} {{");
                builder.AppendLine($"        host {route.Hostname}");
                builder.AppendLine("        path /edge-auth/*");
                builder.AppendLine("    }");
                builder.AppendLine($"    handle @{authReturnMatcherName} {{");
                builder.AppendLine($"        reverse_proxy 127.0.0.1:{Math.Clamp(options.LmsForwardAuthPort, 1, 65535)} {{");
                builder.AppendLine("            header_up Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Proto https");
                builder.AppendLine("            header_up X-Forwarded-Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Port 443");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine();
            }

            var pathPrefix = EdgeGatewayRouteValidator.NormalizePathPrefix(route.TargetPathPrefix);
            if (string.IsNullOrWhiteSpace(pathPrefix))
            {
                builder.AppendLine($"    @{matcherName} host {route.Hostname}");
            }
            else
            {
                builder.AppendLine($"    @{matcherName} {{");
                builder.AppendLine($"        host {route.Hostname}");
                builder.AppendLine($"        path {pathPrefix} {pathPrefix}/*");
                builder.AppendLine("    }");
            }

            builder.AppendLine($"    handle @{matcherName} {{");

            if (route.AuthMode != EdgeGatewayAuthMode.PassThrough)
            {
                builder.AppendLine($"        forward_auth 127.0.0.1:{Math.Clamp(options.LmsForwardAuthPort, 1, 65535)} {{");
                builder.AppendLine("            uri /edge-auth/check");
                builder.AppendLine("            header_up Cookie {http.request.header.Cookie}");
                builder.AppendLine("            header_up X-Forwarded-Proto https");
                builder.AppendLine("            header_up X-Forwarded-Host {host}");
                builder.AppendLine("            header_up X-Forwarded-Uri {uri}");
                builder.AppendLine("            header_up X-Forwarded-Port 443");
                builder.AppendLine("            copy_headers X-LMS-User X-LMS-Email X-LMS-Groups");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(pathPrefix))
            {
                builder.AppendLine($"        uri strip_prefix {pathPrefix}");
                builder.AppendLine();
            }

            builder.Append(BuildReverseProxyBlock(route));
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("    handle {");
        builder.AppendLine("        respond 404");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();

        return builder.ToString();
    }

    public string GenerateCloudflareTunnelSnippet(string domainName)
    {
        var normalizedDomain = EdgeGatewayRouteValidator.NormalizeDomainName(domainName);
        var serviceUrl = ResolveCaddyServiceUrl(options.CaddyLocalServiceUrl);

        return $"""
            ingress:
              - hostname: "*.{normalizedDomain}"
                service: {serviceUrl}
              - service: http_status:404
            """;
    }

    public static string BuildWildcardDnsTarget(string tunnelId) =>
        $"{(tunnelId ?? string.Empty).Trim()}.cfargotunnel.com";

    private static string SanitizeComment(string value) =>
        value.Replace('\r', ' ').Replace('\n', ' ').Trim();

    private static string BuildMatcherName(EdgeGatewayRoute route) =>
        $"edge_route_{route.Id:N}";

    private static string BuildAuthMatcherName(EdgeGatewayRoute route) =>
        $"edge_auth_{route.Id:N}";

    private static string BuildAuthAssetMatcherName(EdgeGatewayRoute route) =>
        $"edge_auth_assets_{route.Id:N}";

    private static string BuildAuthReturnMatcherName(EdgeGatewayRoute route) =>
        $"edge_auth_return_{route.Id:N}";

    private string BuildReverseProxyBlock(EdgeGatewayRoute route)
    {
        var targetUrl = EdgeGatewayRouteValidator.BuildTargetUrl(route);
        var shouldTreatAsLocalLmsHop = IsPassThroughLocalLmsBackend(route);
        var shouldSkipBackendTlsVerification = route.TargetScheme == EdgeGatewayTargetScheme.Https &&
                                               route.SkipUpstreamTlsVerification;

        var builder = new StringBuilder();
        builder.AppendLine($"        reverse_proxy {targetUrl} {{");
        builder.AppendLine(route.UsePublicHostHeader
            ? "            header_up Host {host}"
            : "            header_up Host {upstream_hostport}");
        if (route.StripForwardedFor)
        {
            builder.AppendLine("            header_up -X-Forwarded-For");
        }
        else if (shouldTreatAsLocalLmsHop)
        {
            builder.AppendLine("            header_up X-Forwarded-For 127.0.0.1");
        }

        if (route.UsePublicHostHeader)
        {
            builder.AppendLine("            header_up X-Real-IP {remote_host}");
        }

        builder.AppendLine("            header_up X-Forwarded-Proto https");
        builder.AppendLine("            header_up X-Forwarded-Host {host}");
        builder.AppendLine("            header_up X-Forwarded-Port 443");

        if (shouldSkipBackendTlsVerification)
        {
            builder.AppendLine("            transport http {");
            builder.AppendLine("                tls_insecure_skip_verify");
            builder.AppendLine("            }");
        }

        builder.AppendLine("        }");
        return builder.ToString();
    }

    private bool IsPassThroughLocalLmsBackend(EdgeGatewayRoute route)
    {
        if (route.AuthMode != EdgeGatewayAuthMode.PassThrough ||
            EdgeGatewayRouteValidator.NormalizeTargetPort(route.TargetPort) != Math.Clamp(options.LmsForwardAuthPort, 1, 65535))
        {
            return false;
        }

        var targetHost = EdgeGatewayRouteValidator.NormalizeTargetHost(route.TargetHost);
        if (targetHost.Equals("localhost", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return IPAddress.TryParse(targetHost, out var address) && IPAddress.IsLoopback(address);
    }

    private static string ResolveCaddyServiceUrl(string value) =>
        string.IsNullOrWhiteSpace(value) ? "http://localhost:8443" : value.Trim();

    private static LocalCaddyOrigin ResolveLocalOrigin(string value)
    {
        var serviceUrl = ResolveCaddyServiceUrl(value);
        if (!Uri.TryCreate(serviceUrl, UriKind.Absolute, out var uri))
        {
            return new LocalCaddyOrigin("http://:8443", false);
        }

        var port = uri.IsDefaultPort
            ? uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase) ? 443 : 80
            : uri.Port;
        var scheme = uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase)
            ? Uri.UriSchemeHttps
            : Uri.UriSchemeHttp;
        return new LocalCaddyOrigin($"{scheme}://:{Math.Clamp(port, 1, 65535)}", scheme == Uri.UriSchemeHttps);
    }

    private sealed record LocalCaddyOrigin(string CaddySiteAddress, bool UseInternalTls);
}
