// Copyright (c) Richard D. Kiernan.
// Licensed under the Business Source License 1.1. See LICENSE for details.

namespace LinuxMadeSane.Web.Components.Ui;

public enum UiIconGlyph
{
    Refresh = 0,
    NewFolder = 1,
    Cut = 2,
    Copy = 3,
    Paste = 4,
    Delete = 5,
    PopOut = 6,
    Clear = 7,
    SidebarCollapse = 8,
    SidebarExpand = 9,
    SignOut = 10,
    Plus = 11,
    Connect = 12,
    Disconnect = 13,
    Focus = 14,
    Interrupt = 15,
    Ai = 16,
    Connection = 17,
    Dock = 18,
    FolderOpen = 19,
    Run = 20,
    Send = 21,
    Analyze = 22,
    Zip = 23,
    Unzip = 24,
    Info = 25,
    Edit = 26,
    Chat = 27,
    FolderClosed = 28,
    NetworkMount = 29,
    Save = 30,
    SplitRight = 31,
    SplitBottom = 32,
    TextFile = 33,
    User = 34,
    Group = 35,
    Stop = 36,
    Restart = 37,
    Repair = 38,
    Search = 39,
    Upload = 40,
    Download = 41,
    Lock = 42,
    Unlock = 43,
    Key = 44,
    Website = 45
}
